require('src.set')
require('src.packer')
require('src.keymap')
require('src.null-ls')
require('src.lspconfig')
require('src.lualine')
require('src.tokyonight')
require('src.nvim-tree')
require('src.nvim-treesitter-configs')
require('src.gitsigns')
-- require('src.prettier')
